In [1]:
# NumPy

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11,2.4)

array([0. , 2.4, 4.8, 7.2, 9.6])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
#The essential difference between NumPy linspace and NumPy arange 
#is that linspace enables you to control the precise end value, 
#whereas arange gives you more direct control over the increments between values in the sequence

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#this is identity matrix

In [20]:
np.random.rand(4)

array([0.32425638, 0.86368684, 0.74256268, 0.1412954 ])

In [23]:
# random distribution from standard normal distribution 
# or Gaussian distribution

In [22]:
np.random.randn(2)

array([-0.43360544, -0.42307962])

In [25]:
np.random.randint(1,100,5)

array([ 4, 72, 70, 96, 14])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([29, 39, 17, 21, 24, 26, 17, 35, 20,  8])

In [30]:
# reshape method

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

39

In [33]:
ranarr.argmax()

1

In [34]:
# To get the index value of max, argmax

In [35]:
arr.shape

(25,)

In [36]:
# to find datatype in array

In [37]:
arr.dtype

dtype('int32')

In [38]:
# different calling method

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

8

In [42]:
# NumPy array Indexing

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[8]

8

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
# It slices value based on indexing, as it works in python lists
# includes start value but doesn't include end value

In [50]:
# How Numpy differs is their ability to broadcast

In [51]:
slice_of_arr = arr[0:6]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:] = 99

In [55]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
# Now we made changes in slice of array but it made changes in original array as well.
# Data is not copied, its just a view of original array.

In [61]:
""" 
NumPy does that to avoid memory issues with very large arrays
If you want a copy and not a reference to original array you can
specifically specify copy 
"""

' \nNumPy does that to avoid memory issues with very large arrays\nIf you want a copy and not a reference to original array you can\nspecifically specify a copy \n'

In [62]:
arr_copy = arr.copy()

In [63]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [65]:
arr_copy[:] = 100

In [66]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
# 2d array and nested list

In [69]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
# double bracket indexing, first for row and second for column i

In [75]:
arr_2d[0][2]

15

In [76]:
# single bracket indexing, using comma instead of second bracket

In [77]:
arr_2d[1,2]

30

In [79]:
arr_2d[0:1,1:2]

array([[10]])

In [82]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [84]:
# this means 2 is not included and similarly 1 is included to the end

In [86]:
arr_2d[2,1:]

array([40, 45])

In [87]:
arr = np.arange(1,11)

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
bool_arr = arr > 5

In [91]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [93]:
# So taking an array and using comparison operator on it will give a Boolean array

In [95]:
# this array can be used to conditional select values in original array
# as it returns only values with true condition satisfaction

In [96]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [97]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [99]:
# this is conditional selection in same array, preferred

In [101]:
arr_2d = np.arange(50).reshape(5,10)

In [102]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [103]:
# NumPy Operations

In [104]:
arr = np.arange(0,11)

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [107]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [108]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [109]:
arr / arr

<ipython-input-109-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [110]:
# Here NumPy doesn't give error feedback but instead issue a warning
# in the start which says nan (null object) at the start, everything else it returns a value

In [111]:
# Universal array functions

In [112]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [113]:
np.max(arr)

10

In [114]:
#or
arr.max()

10

In [115]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [116]:
# and a lot more...

In [117]:
#Exercises

In [2]:
import numpy as np

In [6]:
z_arr = np.zeros(5)

In [7]:
z_arr

array([0., 0., 0., 0., 0.])

In [8]:
z_arr = np.ones(10)

In [9]:
z_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
z_arr = np.ones(10)*5

In [12]:
z_arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
z_arr = np.arange(10,51)

In [16]:
z_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
z_arr = np.arange(10,51,2)

In [18]:
z_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
z_arr = np.arange(0,9).reshape(3,3)

In [20]:
z_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
z_arr = np.eye(3)

In [22]:
z_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
from numpy import random

In [27]:
np.random.rand()

0.6985020623796842

In [28]:
np.random.randn(25).reshape(5,5)

array([[ 0.06728407,  0.57057219, -1.77050407, -0.43118742,  0.88667105],
       [-0.81573467, -0.05465689,  0.39191796,  0.40644072,  0.00374204],
       [-1.06044227, -0.19144036,  0.62808854, -1.58699763, -0.05666279],
       [-0.86056897,  1.453461  ,  1.49274865,  0.84939201, -2.1835447 ],
       [-1.72542265,  2.59596175,  1.10837188,  0.63140227,  0.85198411]])

In [40]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [41]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [42]:
mat = np.arange(1,26)

In [60]:
mat.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
mat.sum()

325

In [47]:
mat.std()

7.211102550927978

In [56]:
a = np.sum(mat, axis=0)

In [57]:
a

325

In [58]:
print(a)

325


In [61]:
mat.sum(axis=0)

325

In [62]:
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [63]:
mat = np.arange(1,26).reshape(5,5)

In [64]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])